services:
  adguard:
    image: adguard/adguardhome
    container_name: adguard
    network_mode: host
    volumes:
      - ./adguard/work:/opt/adguardhome/work
      - ./adguard/conf:/opt/adguardhome/conf
    restart: unless-stopped

  traefik:
    image: traefik:v2.10
    container_name: traefik
    network_mode: host
    command:
      - "--api.insecure=true"
      - "--providers.file.filename=/etc/traefik/dynamic_conf.yml"
      - "--entrypoints.web.address=:80"
      - "--log.level=DEBUG"
    volumes:
      - ./traefik_dynamic.yml:/etc/traefik/dynamic_conf.yml
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: nestjs
    network_mode: host
    restart: unless-stopped
    # Labels removed, using explicit file config
